export const BUSCAR_CANCHA = 'BUSCAR_CANCHAS';
export const SELECCIONAR_CANCHA = 'SELECCIONAR_CANCHA';
export const OCULTAR_MODAL_CANCHA = 'OCULTAR_MODAL_CANCHA';
export const CARGAR_CANCHAS_FILTRADAS = 'CARGAR_CANCHAS_FILTRADAS';
export const SELECCIONAR_TURNO = 'SELECCIONAR_TURNO';
export const DESELECCIONAR_TURNO = 'DESELECCIONAR_TURNO';
export const TRAER_CANCHAS = 'TRAER_CANCHAS';
export const BUSCAR_CANCHA_PRECIO = 'BUSCAR_CANCHA_PRECIO';